### PR TITLE
Hello

### PR DESCRIPTION
**Pull request by dr3mro**
thank you for your effort 
I have updated the choco install script to the new project url 
please accept
thnx

### CODE REVIEW

**Comment by Thieum** [comment]
Thanks! Here is the newer version on Chocolatey: https://community.chocolatey.org/packages/visualleakdetector/2.5.1.1#versionhistory

**Comment by Thieum** [comment]
@dr3mro it seems that Microsoft (azure team) has decided to take upon themselves to update the project here : https://github.com/Azure/vld - I'll make that latest version available from there too.

**Comment by dr3mro** [comment]
Even better 
Thanks 🙏 
But when will it hit the choco repos? 
Tried to issue update but gettings same install error

**Comment by Thieum** [comment]
@dr3mro well the package is in moderation, so it's up to the choco team to approve it - it can take some time, especially since it was 4th July.

**Pull request merged**
